name: Scheduled Weather Fetcher

on:
    schedule:
        - cron: '0 * * * *'  # Setiap jam
    workflow_dispatch:  # Memungkinkan trigger manual

jobs:
  update-weather:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install pandas requests

      - name: Run script
        run: python stream.py

      - name: Configure Git
        run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"

      - name: Commit and push changes
        run: |
          git add weather_data.csv
          git commit -m "Update weather data"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
